# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='um_ecomm_dept_units_rept',
            table='PINN_CUSTOM"."UM_ECOMM_DEPT_UNITS_REPT',
        ),
    ]
