# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_auto_20170621_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='um_ecomm_dept_units_rept',
            options={'managed': False, 'ordering': ['account', 'charge_group', 'description']},
        ),
    ]
